# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    serializer:
        serialize_null: true
    view:
        view_response_listener: true
        failed_validation: 422
        empty_content: 204
    exception:
        map_exception_codes: true
        codes:
            'App\Exception\EntityNotFoundException': 404
        messages:
            'App\Exception\EntityNotFoundException': true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    param_fetcher_listener: force
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type:  true
        decoders:
            json: fos_rest.decoder.json
