nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        info:
            title: Splitey
            description: Split bills
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/[^_]
