nelmio_api_doc:
    documentation:
        info:
            title: Splitey
            description: Split bills
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/[^_]
