controllers:
    resource: ../src/Controller/
    type: attribute

app.swagger_ui:
    path: /_doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /_doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
